/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "roman_math_test.check" instead.
 */

#include <check.h>

#line 1 "roman_math_test.check"
#include "roman_math_lib.h"

START_TEST(add_roman_numbers)
{
#line 4
    ck_assert_str_eq(add("I", "I"), "II");
    ck_assert_str_eq(add("IV", "V"), "IX");
    ck_assert_str_eq(add("V","IV"), "IX");
    ck_assert_str_eq(add("CDXCV","XXIX"), "DXXIV");
    ck_assert_str_eq(add("XLIII","LXXXVI"), "CXXIX");

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, add_roman_numbers);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
